spring.application.name=ESPE-Plus

spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev

server.servlet.springcontext-path=/api/v1


server.port=8080


langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

# Niveles de Log para desarrollo
logging.level.org.springframework=DEBUG
logging.level.dev.langchain4j=DEBUG
environment.name=Desarrollo (DEV)